name = "zhouyi-indexer"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
SOLANA_RPC_URL = "https://api.devnet.solana.com"
PROGRAM_ID = "DFqXUJKoErPKr9mmviuvdys1GZ5nYVrgGYgatX5W2MHf"

[[d1_databases]]
binding = "DB"
database_name = "zhouyi"
database_id = "6565ee00-e4a3-4ba3-af6c-08b0d1d701fb"

[triggers]
crons = ["* * * * *"]
